import java.util.Random; 
 
class SharedData { 
    int num; 
    boolean ready = false; 
} 
 
class Producer extends Thread { 
    SharedData data; 
    Producer(SharedData d) {
	  data = d; 
    } 
    public void run() { 
        Random rand = new Random(); 
        for (int i = 0; i < 10; i++) { 
            synchronized (data) { 
                while (data.ready) { 
                    try { data.wait(); } catch (InterruptedException e) {} 
                } 
                data.num = rand.nextInt(100) + 1; 
                System.out.println("Number generated by Producer: " + data.num); 
                data.ready = true; 
                data.notifyAll(); 
            } 
        } 
    } 
}
class Consumer extends Thread { 
    SharedData data; 
    int evenCount = 0; 
    Consumer(SharedData d) { 
        data = d; 
    }  
    public void run() { 
        for (int i = 0; i < 10; i++) { 
            synchronized (data) { 
                while (!data.ready) { 
                    try { data.wait(); } catch (InterruptedException e) {} 
                } 
                if (data.num % 2 == 0) 
                    evenCount++; 
                data.ready = false; 
                data.notifyAll();
				      } 
        } 
        System.out.println("Number even numbers received by Consumer: " + evenCount); 
    } 
} 
 
public class WaitDemo { 
    public static void main(String[] args) { 
        SharedData data = new SharedData(); 
        Producer p = new Producer(data); 
        Consumer c = new Consumer(data); 
        p.start(); 
        c.start(); 
        try { 
            p.join(); 
            c.join(); 
        } catch (InterruptedException e) {} 
    } 
